### ISSUE TITLE
Is there any way to allow external code to modify the structures generated by random_crystal?

### ISSUE THREAD

**Issue by usccolumbia** [qzhu2017/PyXtal#113]
Random_crystal is a great routine to generate random structure for a given formula and space group.
but usually one would like to optimize the coordinates of the generated structure to fine-tune it. 

Is it possible that the PyXtal provide the function that allows external code to modify the coordinate while preserving the symmetry group?

The function call is like this:

spacegroup=195
elements=['Mg','Mn','O']
moles=[4,4,8]
sites=[...]
 C = random_crystal(spacegroup, elements, mols, 1.0,sites=sites)

C.sites[0].coordinate_update(x,y,z)

The key thing is that the coordinate_upate function will check the new (x,y,z) to ensure it won't disrupt the symmetry of the structure C. E.g. if it has special coordinates such as 0.5, 0.5, 0... When it is replaced by (0.343, 0.24, 0.45), then it won't let it happen.

**Comment by qzhu2017** [comment]
@usccolumbia 

Probably, this function has already been implemented. Please check the following script.

```python
>>> from pyxtal import pyxtal
>>> xtal = pyxtal()
>>> xtal.from_random(3, 195, ['Mg', 'Mn', 'O'], [4, 4, 8])
>>> xtal.atom_sites[0].position
array([0.37887622, 0.37887622, 0.37887622])
>>> xtal.atom_sites[0].update([0.35, 0.35, 0.38])
>>> xtal.atom_sites[0].position
array([0.35, 0.35, 0.35])
```
Note that in the above line, the original coordinate is 
`[0.37887622, 0.37887622, 0.37887622]`

We asked to change it to 
`[0.35, 0.35, 0.38]`

It ends up with
`[0.35, 0.35, 0.35]`
due to the symmetry operation `x, x, x` constraint.


Btw, we are now redesigning the way to call the generator in a more universal way. 
From now on, you don't need to explicitly call the modules like `random_crystal`. 
Everything will be called from `pyXtal.pyxtal` class.

**Comment by usccolumbia** [comment]
this is really helpful. Thanks.  we will try it soon.
