### ISSUE TITLE
Wyckoff as a separate class

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#36]
@scottfredericks 

After reading the documents on wyckoff positions
https://github.com/qzhu2017/PyXtal/blob/master/doc/index.rst

I think a better way to organize it should make a separate class.
```python
>>> from pyxtal.crystal import *
>>> sg = 35
>>> index = index_from_letter('b', sg)
>>> ops = get_wyckoff_symmetry(sg)[index][0]
>>> ss_string_from_ops(ops, sg)
'mm2'
```

A human way of doing this should be 
```python
>>> from pyxtal.wyckoff import wyckoff
>>> sg = 35
>>> test = wyckoff(sg)
>>> test.show_letters()
>>> ops = test.get_wyckoff_symmetry('4b')
>>> ops.point_group()
'mm2'
```

We should do it after fixing the issues in speeds

**Comment by qzhu2017** [comment]
@scottfredericks 
This should be done soon.

**Comment by scottfredericks** [comment]
@qzhu2017 
Some updates:
1) I have moved some functionality from crystal.py to the new document symmetry.py. These are functions which have to do with symmetry, like get_wyckoffs, ss_string_from_ops, create_matrix, etc.

2) Inside of symmetry.py, I have created two new classes: Group and Wyckoff_position. The Wyckoff_position class stores the operations, generators, and symmetry for a single Wyckoff position within a symmetry group. The Group class stores a list of Wyckoff_position objects corresponding to the group, as well as lists for the generators and symmetry. There are custom __str__, __repr__, __iter__, and __getitem__ variables for both classes. For the Group class, indexing returns a Wyckoff_position object. For the Wyckoff_position class, indexing returns a SymmOp for a single point in the Wyckoff position. Here is an example of how to use them:
```
>>> from pyxtal.symmetry import *
>>> g = Group(7, dim=2)
>>> g
~~~Layer group # 7~~~
---4e--- site symm: 
---2d--- site symm: 
---2c--- site symm: 
---2b--- site symm: 
---2a--- site symm: 
>>> g.get_wyckoff_position('2c')
Wyckoff position 2c in layer group 7
1/4, 0, z
3/4, 0, -z
>>> g.get_wyckoff_position(1)
Wyckoff position 2d in layer group 7
1/4, 1/2, z
3/4, 1/2, -z
>>> g.print_all()
~~~Layer group # 7~~~
---4e--- site symm: 
x, y, z
-x+1/2, -y, z
-x, -y, -z
x+1/2, y, -z
---2d--- site symm: 
1/4, 1/2, z
3/4, 1/2, -z
---2c--- site symm: 
1/4, 0, z
3/4, 0, -z
---2b--- site symm: 
0, 1/2, 0
1/2, 1/2, 0
---2a--- site symm: 
0, 0, 0
1/2, 0, 0
```
As you see, the site symmetry does not get printed at the moment. I just need to extend ss_string_from_ops to work for groups of any dimensions before I implement it.

Besides this, please let me know if you would like any other functionality, or to change the formatting or names of any of the functions. The reason I called the new class 'Group' instead of 'Wyckoff' is that I would eventually like to make it a more general class for symmetry groups. I should be able to extend the functionality to 0D point groups quite easily.

3) I think I'll be able to implement the new Group and Wyckoff_position classes within the rest of the code by tomorrow evening. (inside of crystal.py, molecular_crystal.py, molecule.py)

4) For accessibility, I will work on some functions for getting the H-M (and possibly Hall) symbol for a given group number, and vice-versa. This should just amount to making a list or two somewhere in the database directory.

**Comment by qzhu2017** [comment]
Excellent. I think it would be also good to get H-M symbols as well. I am happy with the current functionality.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have implemented all changes except the H-M symbols for groups. I will make a separate issue for this. However, I did extend ss_string_from_ops, so we can now see the site symmetry for 2D and 1D Wyckoff positions. I haven't gotten the chance to check the results yet.

The module docs have been updated. I will work on updating the home page documentation tomorrow.

**Comment by qzhu2017** [comment]
@scottfredericks 
```
>>> g = Group(217)
>>> g.print_all()
Traceback (most recent call last):
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/symmetry.py", line 1742, in print_all
    print(self.string_long)
AttributeError: 'Group' object has no attribute 'string_long'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/symmetry.py", line 1757, in print_all
    s += ss_string_from_ops(sp.symmetry_m[0], self.number, dim=self.dim)
NameError: name 'sp' is not defined
```

**Comment by qzhu2017** [comment]
@scottfredericks you need to add these into the test_all.py as well
