### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#49]
@scottfredericks 
I just add a test code for optimization. It works fine. Now I need to implement the method for optimization under symmetry constraints. Please find me tomorrow. I need to know how to find the symmetry information for such task.

**Comment by qzhu2017** [comment]
I am also going to add the function to relax the box shape after the symmetry function is included.

**Comment by qzhu2017** [comment]
I am also adding the two-point steep descent approach in the optimization engine.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have tried adding a basic symmetrization function, but it seems the energies for the random clusters are too high even before using symmetry. If you look at the new script pyxtal/optimize/fire2.py, you will see that the starting energies tend to be very close to 0.

I believe this is because the random clusters are too large. I have printed out the maximum distance (maxr) for the atoms in the structures, and as you can see, the random clusters tend to have atoms much farther from the center than the optimized structure. Perhaps we can reduce the volume used for the lattice generation for clusters.

**Comment by qzhu2017** [comment]
@scottfredericks  I think it is good to reduce the volume factor. But let's do it more carefully. 

In the meantime, I suggest you add the option to symmetrize the force. This is a safer way to control the symmetry. Then let's monitor if the symmetry has changed for each step during the optimization.

**Comment by qzhu2017** [comment]
@scottfredericks , I added a few options to control the optimization in fire2.py.
I think this is also because we didn't have good implementation of FIRE algo. 

I added a comparison results from external optimizers from scipy. The results are very inconsistent at the moment. I will try to figure out the best solution. In the mean time, please try to check if your implementation is correct.

**Comment by scottfredericks** [comment]
@qzhu2017 
I found one more issue with the cluster distance checking, due to not using the absolute coordinates for the generating point. This should be fixed.

I apologize for all of the distance checking issues with clusters; using a non-Euclidean lattice for generating points has resulted in more difficulties than I anticipated. I currently have several debug lines in crystal.py to try and catch any other failed distance checks; if you see any of these get printed, please show me the output.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have changed the behavior of point group lattices. Now, the large lattice matrix is internal to the Lattice class, and used only for generating a point. The given lattice for the point group clusters will always be the Euclidean lattice. Hopefully this will eliminate the issues with conversion back and forth between absolute and fractional coordinates. I still have the debug code in case I missed something.

**Comment by qzhu2017** [comment]
@scottfredericks , I just add the option to output the symmetry information in the script.

However, somehow, Pymatgen also returns the lower symmetry than what we assigned from PyXtal. Could you check if you have the right symmetry? What is is cause of discrepancy?

**Comment by scottfredericks** [comment]
@qzhu2017 
I have changed a couple of lines in symmetrized_force. Now, instead of applying the first wp op to the generating point and then using wp.generators_m, we just plug in the generating point directly into the standard wp operations. This seems to preserve the symmetry over time.

The only exception is C7 and D7; sometimes Pymatgen the found symmetry is not correct. I think this may just be because pymatgen has difficulty with 7-fold symmetry. We can use the check_struct_group function from test_all.py to see if this is the case.

**Comment by qzhu2017** [comment]
@scottfredericks where is the check_struct_group function?
Also, here you assume that the atoms are already sorted by the Wyckoff type. I am thinking about some more general application. Suppose I give you a structure without symmetry information, can you convert it to our structural type?

**Comment by scottfredericks** [comment]
@qzhu2017 
I have slightly modified check_struct_group so that it can accept lists of coordinates instead of random_crystal objects. I have added a copy of it to fire2.py .

For each final structure, we check if the initial point group symmetry still remains. check_struct_group is not yet general enough to check the symmetry of an arbitrary orientation/setting. However, since the optimization seems to preserve the orientation, check_struct_group should be accurate for the moment.

For crystal structures, it is relatively straightforward to analyze the symmetry using spglib or pymatgen. For point group clusters, pymatgen's PointGroupAnalyzer is a good base to convert a list of coordinates/species into our own structure type. Using these two functions, it shouldn't be too hard to import structures and get their symmetry. We could create our own symmetry analyzer functions eventually, but the different orientations/settings would take some time to implement correctly. I would like to talk to you in person to get a better idea of how to organize the new class(es) for our structure type.

Using the output from check_struct_group, it seems that PointGroupAnalyzer is correct. Some structures starting with C7 do end up as C1. However, if we turn on symmetrization of the position after each step, the problem goes away, and both PyXtal and PMG recognize the final structure as having 7-fold symmetry. So, either PyXtal's symmetry information is incorrect, or there is a numerical issue for 7-fold rotations.

**Comment by qzhu2017** [comment]
@scottfredericks 
I just created the optimization model for LJ, 
PyXtal/pyxtal/interface/LJ.py

This function now only works for elementary systems for 3D crystal. Could you please include the function to symmetrize the lattice matrix as well.

Also, I am thinking these symmetrize function should go to our `symmetry.py`, `operation.py` or our `PyXtal structure class`.

After this is done, I will reorganize the interface and optimize codes to make them more logical.

**Comment by scottfredericks** [comment]
@qzhu2017 
Inside of LY.py, I have updated the symmetrized_coords function, and have added a new function called symmetrized_force. I would like to test these out, but I am getting an error:
```Traceback (most recent call last):
  File "LJ.py", line 265, in <module>
    eng, enth, force, stress = test.calc(crystal)
  File "LJ.py", line 57, in calc
    [r2, r] = get_neighbors(struc, i, self.rcut)
  File "LJ.py", line 21, in get_neighbors
    fcoords, center=center, r=rcut, zip_results=False)
ValueError: not enough values to unpack (expected 4, got 3)```

**Comment by scottfredericks** [comment]
@qzhu2017 
I have added the function symmetrized_stress to LJ.py . It uses symmetry information which I added to the pyxtal.crystal.lattice class. I have not gotten the chance to test it yet.

The basic idea is that we define a 3x3 "stress normalization" matrix which will be multiplied with the stress (using np.multiply, not np.dot). The values of this matrix are 1's and 0's, which will either allow or filter out components of the stress.

First, we make the stress matrix lower-diagonal (which is the shape of lattice matrices in PyXtal) by setting the upper-diagonal components to 0 and adding them to the lower-diagonal components. Then, we multiply by our matrix.

Finally, if needed, we normalize the on-diagonal components. For lattices with a=b, we multiply the [0][0] and [1][1] stress components and take the square root, then set the [0][0] and [1][1] components to this value. For lattices with a=b=c, we multiply all 3 diagonal elements, then set them to the cube root of the product.

I haven't tested it yet, since I still get the error which I mentioned above.

**Comment by qzhu2017** [comment]
@scottfredericks 
(base) qiangzhu@deptanonpool-238:~/Desktop/github/PyXtal/pyxtal/interface$ python LJ.py 

Before relaxation Space group:   19  Energy:        120.1  Enthalpy:        120.1

Traceback (most recent call last):
  File "LJ.py", line 296, in <module>
    dyn1.run(500)
  File "LJ.py", line 172, in run
    self.step()
  File "LJ.py", line 142, in step
    f[3:, :] = self.symmetrized_force(f[3:, :])
  File "LJ.py", line 238, in symmetrized_force
    inverse_ops = ws.wp.inverse_generators_m
AttributeError: 'Wyckoff_position' object has no attribute 'inverse_generators_m'

**Comment by scottfredericks** [comment]
@qzhu2017 
I got that bug and made some changes to symmetry.py that seems to have fixed things on my end. Also, I just made a commit to symmetry.py a few minutes ago, and a small syntax fix for LJ.py a moment ago.

**Comment by scottfredericks** [comment]
@qzhu2017 
Note that in the latest commit I also turned on stress symmetrization on line 141 of LJ.py

**Comment by qzhu2017** [comment]
@scottfredericks After your implementation, it seems that the results become worse.
```
(base) qzhu@cms:/scratch/qzhu/github/PyXtal/pyxtal/interface$ python LJ.py 
/scratch/qzhu/anaconda3/lib/python3.6/site-packages/pymatgen/io/cif.py:37: UserWarning: Please install optional dependency pybtex if youwant to extract references from CIF files.
  warnings.warn("Please install optional dependency pybtex if you"

Before relaxation Space group:              19   Energy:        19.16  Enthalpy:        19.16
After relaxation without symm Space group:  194  Energy:      -0.3167  Enthalpy:      -0.3166
After relaxation with symm Space group:       1  Energy:      -0.1455  Enthalpy:      -0.1454

Before relaxation Space group:              19   Energy:        319.6  Enthalpy:        319.6
After relaxation without symm Space group:  194  Energy:      -0.3167  Enthalpy:      -0.3166
After relaxation with symm Space group:       1  Energy:      -0.1514  Enthalpy:      -0.1512

Before relaxation Space group:              19   Energy:        36.42  Enthalpy:        36.42
After relaxation without symm Space group:  225  Energy:      -0.3152  Enthalpy:      -0.3151
After relaxation with symm Space group:       1  Energy:       -0.288  Enthalpy:      -0.2879

Before relaxation Space group:              19   Energy:        19.84  Enthalpy:        19.84
After relaxation without symm Space group:  225  Energy:      -0.3152  Enthalpy:      -0.3151
After relaxation with symm Space group:       1  Energy:      -0.3073  Enthalpy:      -0.3072

Before relaxation Space group:              19   Energy:    6.132e+04  Enthalpy:    6.132e+04
After relaxation without symm Space group:  225  Energy:      -0.3152  Enthalpy:      -0.3151
After relaxation with symm Space group:       1  Energy:      -0.2743  Enthalpy:      -0.2742

Before relaxation Space group:              19   Energy:    5.268e+03  Enthalpy:    5.268e+03
After relaxation without symm Space group:  194  Energy:      -0.3167  Enthalpy:      -0.3166
After relaxation with symm Space group:     194  Energy:      -0.3167  Enthalpy:      -0.3166

Before relaxation Space group:              19   Energy:    5.874e+03  Enthalpy:    5.874e+03
After relaxation without symm Space group:  225  Energy:      -0.3152  Enthalpy:      -0.3151
After relaxation with symm Space group:       1  Energy:      -0.1738  Enthalpy:      -0.1736

Before relaxation Space group:              19   Energy:        906.9  Enthalpy:        906.9
After relaxation without symm Space group:  225  Energy:      -0.3152  Enthalpy:      -0.3151
After relaxation with symm Space group:       1  Energy:      -0.2041  Enthalpy:       -0.204

Before relaxation Space group:              19   Energy:    1.621e+03  Enthalpy:    1.621e+03
After relaxation without symm Space group:  225  Energy:      -0.3152  Enthalpy:      -0.3151
After relaxation with symm Space group:       1  Energy:      -0.2571  Enthalpy:       -0.257

Before relaxation Space group:              19   Energy:    1.143e+03  Enthalpy:    1.143e+03
After relaxation without symm Space group:  194  Energy:      -0.3167  Enthalpy:      -0.3166
After relaxation with symm Space group:       1  Energy:      -0.1266  Enthalpy:      -0.1264
```
Two issues,
- When I enabled the symmetry option, sometimes it gets P1 symmetry, whereas the no symmetry constraint hit the higher space group.
- Sometimes, the energy for the initial composition is still too.large. I wonder if there exist some short distances.

Btw, it reminds me that we need to add a function like check short distances in our own structure class. This way we can easily check what happened.

**Comment by qzhu2017** [comment]
@scottfredericks 
it turns out this is not the fault due to symmetrization function.
We need to take care of the change in box when calculating dr. The symmetry in crystal is valid for fractional coordinates. Now this should be fixed.
