### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#52]
@scottfredericks 
I just noticed two bugs,
1, Right now, you will easily fail when you run the test_all.py due to the detection of small distances.
2, It seems that I am unable to generate even FCC structure for 3D crystal.
```python 
from pyxtal.crystal import random_crystal
crystal = random_crystal(225, ['C'], [4], 1.0)
```
/anaconda3/lib/python3.6/site-packages/pyxtal/operations.py:52: UserWarning: Error: the stoichiometry is incompatible with the wyckoff sites choice
  warn(text)

**Comment by qzhu2017** [comment]
For 2, I just realized I should put numIons=[1], but it still failed.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have fixed the issue for check_compatible; FCC should work now.

The distance check error messages were due to the warning not checking for the right conditional; it should be fixed now.

However, I have noticed a new bug. In test_all.py, within check_struct_group, I check the type of the input. I was using
```type(crystal) == random_crystal```
I have updated it to
```isinstance(crystal, (random_crystal, molecular_crystal))```
For both cases, I get the error
```Traceback (most recent call last):
  File "test_all.py", line 1524, in <module>
    eval(modules_lib[module])
  File "<string>", line 1, in <module>
  File "test_all.py", line 605, in test_atomic_1D
    if check_struct_group(rand_crystal, num, dim=1):
  File "test_all.py", line 88, in check_struct_group
    if isinstance(crystal, (random_crystal, molecular_crystal)):
NameError: name 'random_crystal' is not defined```
But the strange thing is that I only seem to get this bug for the atomic 1D case. I will try to figure this out ASAP.

**Comment by scottfredericks** [comment]
@qzhu2017 
I am able to run test_all.py without issue now; I will close this issue.
