### ISSUE TITLE
two bugs in 2d crystal

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#60]
@scottfredericks I noticed two bugs in the 2d-crystal module.
Try to run the following script. 
```python
from pyxtal.crystal import random_crystal_2D, Lattice

gb_cell = Lattice.from_para(3.83958982,19.95109395, 14, 90, 90, 90)
crystal = random_crystal_2D(2, ['Si'], [50], 1.0, thickness=14, lattice=gb_cell)
if crystal.valid:
    crystal.to_file('poscar')

```
-1, the code no longer works after I upgrade the code based on your recent commit
-2, I executed the old script and got very funny results. 

Please have a look and fix this issue at your earliest convenience.

**Comment by qzhu2017** [comment]
@scottfredericks  Please don't forget to use the `git status` command when you made the commits. I guess you didn't commit all the necessary files from your local repo last time.

**Comment by scottfredericks** [comment]
@qzhu2017 
For some reason, pyxtal does not always get freshly re-built when I do python setup.py install. I have to go in and manually delete both the anaconda files and build directory, then re-install. So, I didn't get this error when I ran test_all.py.

I have tried to eliminate the calls to pyxtal.database.layergroup (which was deprecated). I think your script should run now. It will take me just a bit longer to remove the calls to layergroup within test_all.py, though. I will respond here once I do.

**Comment by qzhu2017** [comment]
You will get a file called 'Si50.poscar'.
The lattice of the 3rd dimension is 24, which I asked for 14. I guess you added 10 A vacuum. 
But when you look at the structure, I don't see vacuum here.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/29445366/56071916-9d51fa00-5d46-11e9-92de-a7b1a682c8b5.png">

**Comment by scottfredericks** [comment]
@qzhu2017 
The problem was that the provided lattice does not have the correct PBC. It was assumed that if a custom lattice is provided, the PBC will be the same as the default PBC for the symmetry group. However, that was not the case here, since the default PBC for a Lattice is [1,1,1]. I forgot that most users wouldn't know or think to input the exact value for PBC for 2D and 1D crystals.

I added a few lines which convert the custom Lattice's PBC to the default for the symmetry group. If this occurs, then we output a warning saying that the PBC was converted. The warning is just in case a user was intentionally trying to use a custom PBC value.

You should be able to see the added vacuum now. Let me know if it still doesn't look right.

One potential problem with the current implementation is that the PBC of the original random_crystal object is not reflected in the output structure, which is periodic and has vacuum added by default. This could be a problem if we create an XStruct object and try to re-generate a new structure using the symmetry information. We will also need to change this before we can do symmetric optimization on 1D and 2D crystals. I can create an issue for this problem.
