### ISSUE TITLE
Add a GULP interface 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#82]
The GULP interface is needed for quick test of optimization methods

**Comment by yanxon** [comment]
@qzhu2017 

Here is the result of that I got.
![Figure_1](https://user-images.githubusercontent.com/32254481/91765753-57414480-eb8e-11ea-84f5-cfcc021e9ad8.png)

200 runs of BO: 27302 s
200 runs of random: 78142 s

# of PyXtal random_crystal calls for BO: 279760 calls
# of PyXtal random_crystal calls for Random: 35901 calls

At the first glance, it seems like BO only provide tiny improvement in comparison to random. I believe the problem is that the GULP Tersoff is not a suitable potential for C. For example, P6_3/mmc and Cmce has the same ground state energy which is -7.395519 eV/atom. This may confused the BO algorithm, since we are trying to optimize for the energy and not the space group. Truly, C only has 1 ground state with the global minimum energy. I believe if we use VASP as the optimizer, BO will improve significantly.

Second, if you look at the first bar in the graph for both BO and random, it seems like random performs better than BO. This may be due to BO algorithm needs some training structures to be able to perform well. Moreover, since GULP Tersoff is not good, the result is worsen.

**Comment by qzhu2017** [comment]
Can you check the structures of Cmce and P63/mmc? If they are the same structures, probably it is not a good idea to use the space group as the criterion to check if you find the ground state structure in the script.

**Comment by yanxon** [comment]
@qzhu2017 

Sorry I was wrong. The space group is not Cmce after optimization. It's actually P2_1/m. Nevertheless, either P2_1/m or Cmce doesn't matter.

Here is the structure for P2_1/m:
![struc_7](https://user-images.githubusercontent.com/32254481/91778854-b1e79a00-eba8-11ea-8f10-b0ede01cfe68.jpg)

This is P63/mmc.
![struc_2](https://user-images.githubusercontent.com/32254481/91779001-202c5c80-eba9-11ea-8357-40c942478cd1.jpg)

They are both ABAB-type layer, shifted differently.

I can run both random and BO again. This time I will stop whenever I found -7.395519 eV/atom regardless the space group. Do you think this is a good idea?

**Comment by yanxon** [comment]
@qzhu2017 

I rerun the random and BO again. This time the algorithm will stop whenever it found a structure with -7.395519 eV/atom regardless the space group.

![Figure_1](https://user-images.githubusercontent.com/32254481/91934795-0c642180-eca1-11ea-8bea-9276d7f80aaa.png)

In this case, they perform more or less the same in my opinion.

**Comment by qzhu2017** [comment]
@yanxon Can you upload your code? Also make sure that the code is organized well.
